// yTrader native MT5 bridge. Attach once to any chart on a DEMO account.
// In MT5: Tools > Options > Expert Advisors > allow WebRequest for
// Raw loopback socket to 127.0.0.1:5001. The EA refuses non-DEMO orders.
#property strict
#property version   "1.000"

input string SidecarHost = "127.0.0.1";
input int SidecarPort = 5001;
input string Symbols = "EURUSD,GBPUSD";
input bool EnableOrders = false;
input int PollMilliseconds = 500;
input int SlippagePoints = 20;

string Trim(const string s) { string r=s; StringTrimLeft(r); StringTrimRight(r); return r; }
string ModeName() { long m=AccountInfoInteger(ACCOUNT_TRADE_MODE); if(m==ACCOUNT_TRADE_MODE_DEMO)return "DEMO"; if(m==ACCOUNT_TRADE_MODE_CONTEST)return "CONTEST"; if(m==ACCOUNT_TRADE_MODE_REAL)return "REAL"; return "UNKNOWN"; }
bool Http(const string method,const string path,const string body,string &reply,int &code) { int sock=SocketCreate();if(sock==INVALID_HANDLE){Print("yTrader socket create failed: ",GetLastError());return false;}if(!SocketConnect(sock,SidecarHost,SidecarPort,5000)){Print("yTrader socket connect failed: ",GetLastError(),". Allow ",SidecarHost," in MT5 settings.");SocketClose(sock);return false;}string req=method+" "+path+" HTTP/1.1\r\nHost: "+SidecarHost+"\r\nConnection: close\r\nContent-Length: "+(string)StringLen(body)+"\r\n\r\n"+body;char send[];int len=StringToCharArray(req,send)-1;if(SocketSend(sock,send,len)!=len){Print("yTrader socket send failed: ",GetLastError());SocketClose(sock);return false;}uchar received[];int got=SocketRead(sock,received,65536,5000);SocketClose(sock);if(got<0){Print("yTrader socket read failed: ",GetLastError());return false;}string raw=CharArrayToString(received,0,got,CP_UTF8);int split=StringFind(raw,"\r\n\r\n");reply=(split<0?raw:StringSubstr(raw,split+4));code=StringToInteger(StringSubstr(raw,9,3));if(code<200||code>=300){Print("yTrader HTTP ",method," ",path," returned ",code,": ",reply);return false;}return true; }
string Js(const string b,const string k) { string t="\""+k+"\":\"";int p=StringFind(b,t);if(p<0)return "";p+=StringLen(t);int e=StringFind(b,"\"",p);return e<0?"":StringSubstr(b,p,e-p); }
double Jn(const string b,const string k) { string t="\""+k+"\":";int p=StringFind(b,t);if(p<0)return 0;p+=StringLen(t);int e=p;while(e<StringLen(b)&&StringFind("0123456789.-",StringSubstr(b,e,1))>=0)e++;return StringToDouble(StringSubstr(b,p,e-p)); }
string E(const string s) { string r=s;StringReplace(r,"\\","\\\\");StringReplace(r,"\"","\\\"");return r; }
string Pos(const string s) { string out="[";bool first=true;for(int i=0;i<PositionsTotal();i++){ulong t=PositionGetTicket(i);if(t==0||PositionGetString(POSITION_SYMBOL)!=s)continue;if(!first)out+=",";first=false;out+="{\"ticket\":"+(string)t+",\"type\":"+(string)PositionGetInteger(POSITION_TYPE)+",\"volume\":"+DoubleToString(PositionGetDouble(POSITION_VOLUME),2)+",\"price_open\":"+DoubleToString(PositionGetDouble(POSITION_PRICE_OPEN),_Digits)+"}";}return out+"]"; }
void Publish() { string a[];int n=StringSplit(Symbols,',',a);string infos="",poss="",prices="";for(int i=0;i<n;i++){string s=Trim(a[i]);if(s==""||!SymbolSelect(s,true))continue;MqlTick t;SymbolInfoTick(s,t);if(infos!=""){infos+=",";poss+=",";prices+=",";}long m=SymbolInfoInteger(s,SYMBOL_TRADE_MODE);infos+="\""+E(s)+"\":{\"contract_size\":"+DoubleToString(SymbolInfoDouble(s,SYMBOL_TRADE_CONTRACT_SIZE),2)+",\"volume_min\":"+DoubleToString(SymbolInfoDouble(s,SYMBOL_VOLUME_MIN),2)+",\"volume_max\":"+DoubleToString(SymbolInfoDouble(s,SYMBOL_VOLUME_MAX),2)+",\"volume_step\":"+DoubleToString(SymbolInfoDouble(s,SYMBOL_VOLUME_STEP),2)+",\"trade_allowed\":"+((m!=SYMBOL_TRADE_MODE_DISABLED&&m!=SYMBOL_TRADE_MODE_CLOSEONLY)?"true":"false")+"}";poss+="\""+E(s)+"\":"+Pos(s);prices+="\""+E(s)+"\":{\"bid\":"+DoubleToString(t.bid,_Digits)+",\"ask\":"+DoubleToString(t.ask,_Digits)+"}";}string j="{\"health\":{\"connected\":"+(TerminalInfoInteger(TERMINAL_CONNECTED)?"true":"false")+",\"login\":"+(string)AccountInfoInteger(ACCOUNT_LOGIN)+",\"server\":\""+E(AccountInfoString(ACCOUNT_SERVER))+"\",\"trade_mode\":\""+ModeName()+"\"},\"account\":{\"balance\":"+DoubleToString(AccountInfoDouble(ACCOUNT_BALANCE),2)+",\"equity\":"+DoubleToString(AccountInfoDouble(ACCOUNT_EQUITY),2)+",\"currency\":\""+E(AccountInfoString(ACCOUNT_CURRENCY))+"\",\"trade_allowed\":"+(AccountInfoInteger(ACCOUNT_TRADE_ALLOWED)?"true":"false")+"},\"symbols\":{"+infos+"},\"positions\":{"+poss+"},\"prices\":{"+prices+"}}";string r;int c;Http("POST","/ea/state",j,r,c); }
void Result(const string id,const string x) { string r;int c;Http("POST","/ea/order_result","{\"id\":\""+E(id)+"\","+x+"}",r,c); }
void Poll() { string b;int c;if(!Http("GET","/ea/next_order","",b,c)||c==204||b=="")return;string id=Js(b,"id"),s=Js(b,"symbol"),side=Js(b,"side");double vol=Jn(b,"volume_lots");if(id==""||s==""||vol<=0){if(id!="")Result(id,"\"error\":\"bad command\"");return;}if(!EnableOrders){Result(id,"\"error\":\"EA EnableOrders is false\"");return;}if(ModeName()!="DEMO"){Result(id,"\"error\":\"EA refuses non-demo account\"");return;}if(!SymbolSelect(s,true)){Result(id,"\"error\":\"unknown symbol\"");return;}MqlTick t;if(!SymbolInfoTick(s,t)){Result(id,"\"error\":\"no tick\"");return;}MqlTradeRequest q={};MqlTradeResult z={};q.action=TRADE_ACTION_DEAL;q.symbol=s;q.volume=vol;q.type=(side=="SELL"?ORDER_TYPE_SELL:ORDER_TYPE_BUY);q.price=(side=="SELL"?t.bid:t.ask);q.deviation=SlippagePoints;q.magic=(ulong)Jn(b,"magic");q.comment=Js(b,"comment");q.type_time=ORDER_TIME_GTC;long f=SymbolInfoInteger(s,SYMBOL_FILLING_MODE);q.type_filling=((f&SYMBOL_FILLING_IOC)!=0?ORDER_FILLING_IOC:((f&SYMBOL_FILLING_FOK)!=0?ORDER_FILLING_FOK:ORDER_FILLING_RETURN));if(!OrderSend(q,z)||z.retcode!=TRADE_RETCODE_DONE){Result(id,"\"error\":\"retcode="+(string)z.retcode+" "+E(z.comment)+"\"");return;}Result(id,"\"ticket\":"+(string)z.order+",\"price\":"+DoubleToString(z.price,_Digits)+",\"volume\":"+DoubleToString(z.volume,2)); }
int OnInit(){if(ModeName()!="DEMO"){Print("yTrader native bridge refuses non-demo accounts.");return INIT_FAILED;}EventSetMillisecondTimer(MathMax(PollMilliseconds,250));Publish();Print("yTrader native bridge ready; EnableOrders=",EnableOrders);return INIT_SUCCEEDED;}
void OnTimer(){Publish();Poll();}
void OnDeinit(const int reason){EventKillTimer();}
